import { Subject } from 'rxjs';

export class SalesStatus {
  value:
    | SALES_ENUM.INITIALIZE_SALES
    | SALES_ENUM.ADDITIONAL_BUYER
    | SALES_ENUM.PRIMARY_BUYER
    | SALES_ENUM.SALES_DETAILS_INFO
    | SALES_ENUM.INVESTER_REVIEW
    | SALES_ENUM.GENERATE_DOCS
    | SALES_ENUM.RECORD_DEED
    | SALES_ENUM.RECEIVED_DOC
    | SALES_ENUM.NOTE_DETAILS
    | SALES_ENUM.CONFIRM_PAYMENT
    | SALES_ENUM.complete
    | null = SALES_ENUM.INITIALIZE_SALES;
}

export enum SALES_ENUM {
  INITIALIZE_SALES = 1,
  ADDITIONAL_BUYER = 2,
  PRIMARY_BUYER = 3,
  SALES_DETAILS_INFO = 4,
  INVESTER_REVIEW = 5,
  GENERATE_DOCS = 6,
  RECEIVED_DOC = 7,
  NOTE_DETAILS = 8,
  CONFIRM_PAYMENT = 9,
  RECORD_DEED = 10,
  complete = 11,
}

export class SalesModel {
  saleType = new Subject();
}
